
package server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RecursoNotFound", targetNamespace = "http://server/")
public class RecursoNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RecursoNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RecursoNotFound_Exception(String message, RecursoNotFound faultInfo) {
        super();
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RecursoNotFound_Exception(String message, RecursoNotFound faultInfo, Throwable cause) {
        super();
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.RecursoNotFound
     */
    public RecursoNotFound getFaultInfo() {
        return faultInfo;
    }

}
