
package server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UserNotFound", targetNamespace = "http://server/")
public class UserNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UserNotFound_Exception(String message, UserNotFound faultInfo) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UserNotFound_Exception(String message, UserNotFound faultInfo, Throwable cause) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.UserNotFound
     */
    public UserNotFound getFaultInfo() {
        return faultInfo;
    }

}
