
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VendasWSService", targetNamespace = "http://server/", wsdlLocation = "http://erebus:8080/Trabalho2Server/VendasWSService?wsdl")
public class VendasWSService
    extends Service
{

    private final static URL VENDASWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VENDASWSSERVICE_EXCEPTION;
    private final static QName VENDASWSSERVICE_QNAME = new QName("http://server/", "VendasWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://erebus:8080/Trabalho2Server/VendasWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENDASWSSERVICE_WSDL_LOCATION = url;
        VENDASWSSERVICE_EXCEPTION = e;
    }

    public VendasWSService() {
        super(__getWsdlLocation(), VENDASWSSERVICE_QNAME);
    }

    public VendasWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENDASWSSERVICE_QNAME, features);
    }

    public VendasWSService(URL wsdlLocation) {
        super(wsdlLocation, VENDASWSSERVICE_QNAME);
    }

    public VendasWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENDASWSSERVICE_QNAME, features);
    }

    public VendasWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendasWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VendasWS
     */
    @WebEndpoint(name = "VendasWSPort")
    public VendasWS getVendasWSPort() {
        return super.getPort(new QName("http://server/", "VendasWSPort"), VendasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VendasWS
     */
    @WebEndpoint(name = "VendasWSPort")
    public VendasWS getVendasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "VendasWSPort"), VendasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENDASWSSERVICE_EXCEPTION!= null) {
            throw VENDASWSSERVICE_EXCEPTION;
        }
        return VENDASWSSERVICE_WSDL_LOCATION;
    }

}
