
package server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TokenValidNotFoundException", targetNamespace = "http://server/")
public class TokenValidNotFoundException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TokenValidNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TokenValidNotFoundException_Exception(String message, TokenValidNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TokenValidNotFoundException_Exception(String message, TokenValidNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.TokenValidNotFoundException
     */
    public TokenValidNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
