
package cobaia1server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://cobaia1server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "pong", targetNamespace = "")
    @RequestWrapper(localName = "pingPong", targetNamespace = "http://cobaia1server/", className = "cobaia1server.PingPong")
    @ResponseWrapper(localName = "pingPongResponse", targetNamespace = "http://cobaia1server/", className = "cobaia1server.PingPongResponse")
    @Action(input = "http://cobaia1server/Server/pingPongRequest", output = "http://cobaia1server/Server/pingPongResponse")
    public String pingPong(
        @WebParam(name = "text", targetNamespace = "")
        String text);

    /**
     * 
     * @param text
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "pong3", targetNamespace = "")
    @RequestWrapper(localName = "ping3", targetNamespace = "http://cobaia1server/", className = "cobaia1server.Ping3")
    @ResponseWrapper(localName = "ping3Response", targetNamespace = "http://cobaia1server/", className = "cobaia1server.Ping3Response")
    @Action(input = "http://cobaia1server/Server/ping3Request", output = "http://cobaia1server/Server/ping3Response")
    public List<String> ping3(
        @WebParam(name = "text", targetNamespace = "")
        String text);

}
