
package cobaia3server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationWS", targetNamespace = "http://cobaia3server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationWS {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://cobaia3server/", className = "cobaia3server.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://cobaia3server/", className = "cobaia3server.AuthenticateResponse")
    @Action(input = "http://cobaia3server/AuthenticationWS/authenticateRequest", output = "http://cobaia3server/AuthenticationWS/authenticateResponse")
    public boolean authenticate();

}
